services:
  flutter:
    image: ghcr.io/cirruslabs/flutter:stable
    restart: unless-stopped
    container_name: flutter_web
    working_dir: /app
    volumes:
      - ./web_app:/app
    expose:
      - "8000"  # Expose Flutter web server
    stdin_open: true
    tty: true
    environment:
      - API_URL=${API_URL}
    # Uncomment when needed
    command: >
      bash -c "flutter pub get &&
               flutter run -d web-server --web-port=8000 --web-hostname=0.0.0.0 --dart-define=API_URL=$API_URL"
    networks:
      - scoobydoo
    depends_on:
      - python

#   Run commands if you want to auto-reload
#   docker-compose run --service-ports flutter
#   It runs flutter in interactive mode. Other services are running in background